### ISSUE TITLE
DSP MOD BUGS

### ISSUE THREAD

**Issue by SeanAshe** [waRNing525/DSP-MODs#1]
About FactoryMultiplier MOD

**Comment by SeanAshe** [comment]
<FactoryMultiplier> mod would force charging power of IPL to 0 and SPL to 400 .
When I try to change the charging power ,they would not to be effected.

**Comment by SeanAshe** [comment]
FactoryMultiplier MOD

**Comment by waRNing525** [comment]
Thanks for your report,it fixed in 2.1.1
